// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0ja7cY_ejta8vpQ8gQ1Xowh5OLeSmq4',
    appId: '1:119323746394:web:33fa4f0ec6d62e4f12b863',
    messagingSenderId: '119323746394',
    projectId: 'project101-20c5e',
    authDomain: 'project101-20c5e.firebaseapp.com',
    storageBucket: 'project101-20c5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_tV36xxCxznLPp_Ir4udhO-xEmPNDirs',
    appId: '1:119323746394:android:8d51563df4f6bfe512b863',
    messagingSenderId: '119323746394',
    projectId: 'project101-20c5e',
    storageBucket: 'project101-20c5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7a52CwbkL0KUYkhNrkjwlaouxeCruILM',
    appId: '1:119323746394:ios:157a975c9fd24cb112b863',
    messagingSenderId: '119323746394',
    projectId: 'project101-20c5e',
    storageBucket: 'project101-20c5e.appspot.com',
    iosBundleId: 'com.example.project123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7a52CwbkL0KUYkhNrkjwlaouxeCruILM',
    appId: '1:119323746394:ios:01d3e4e09af3a17012b863',
    messagingSenderId: '119323746394',
    projectId: 'project101-20c5e',
    storageBucket: 'project101-20c5e.appspot.com',
    iosBundleId: 'com.example.project123.RunnerTests',
  );
}
